bolt/docs

source/content-fetching.md

This issue came up on the irc today - 
nmarques attempted to use {% setcontent members = 'staff' where {position: "!''"} %} to return records where staff was not empty, but found it didn't work. Instead, nmarques figured out that '!' worked: {% setcontent members = 'staff' where {position: '!'} %} 
Since this seems to me to be an unexpected behavior, I figured it should be documented. (Alternatively if it's a bug, then an issue might be opened?)

include where clause checking if a field is empty

---

source/installation.md

Bolt back-end loads Source Sans with woff2 extension.

added .woff2 access permission into nginx configuration

---

source/howto/boilerplate-for-multilingual-websites.md
source/howto/building-multilingual-websites.md

Fixes https://github.com/bolt/bolt/issues/3414

Assign return value from app.config.set() to a variable so it's not output to the browser

---

source/howto/installing-local-extensions.md

After following the steps of the How To document 'Installing Local Extensions' i _could_ actually see my extension in the Extend page.
I removed the statement that local extensions do not appear in the Extend page and added an additional sentence in Step 3 stating the opposite.

Local extensions do appear in Extend page

---

source/howto/resource-contenttype.md

Dynamic pages only can be used as `notfound` handler.

Remark for 404 handling

---

source/installation.md

You may also want to cross-link the items to the pages where they are explained more in detail.
I was also wondering if it is a good idea to add something like "After changing this file, reload the website to see the effect (or for contenttypes: update the database)".

Add 'where-goes-what' section to the installation instructions.

---

source/building-templates.md

At [Template Specific Fields](https://docs.bolt.cm/building-templates#template-specific-fields) section there is a broken image.
I changed `/bolt-docs/files/templatefields-notification.png` to `/files/templatefields-notification.png` as the image below.

Fixed path to image

---

source/nut.md

This is the actual nut output in the Git version of Bolt (2.3.0 alpha 1).
Note that the user:reset-password command is an open PR https://github.com/bolt/bolt/pull/3560, this PR should not be merged until the code is merged.

Update nut output

---

source/extensions/config.md
source/howto/installing-local-extensions.md

after some minutes to discover why local extensions not been autoloaded... 
why the composer not load my local extension classes? I created the composer file and execute the `composer dump-autload`, but why doesn't load?
So, :boom: I had an idea, I did add the vendor/autload.php in my init.php file from my local extension and it solved my problem.
It works good for me and it can help many people which have local extension!!
If I forgot to change others places, tell me, please!!

add tip to autload local extension

---

source/contenttypes-and-records.md

The docs are showing `template` in the example `contenttypes.yml` file. This was changed to `record_template` as described in the bottom of the page.

Update contenttypes example to use record_template

---

source/extensions/testing.md
source/extensions/unit-testing.md

This is the updated extension unit testing documentation that applies to Bolt 2.2.6 and the upcoming 2.3.0.
Reference PRs:
https://github.com/bolt/bolt/pull/3850
https://github.com/bolt/bolt/pull/3870
https://github.com/bolt/bolt/pull/3874

Update extension PHPUnit docs

---

source/installation.md

The current documentation for config_local.yml seemed a little ambiguous. I added a sentence to clarify that Bolt doesn't have an environment setting and that it's up to the deployment process to keep config_local.yml off the server.

Clarfified handling of config_local.yml

---

source/templatetags.md

direct access to a config value with the dot notation no longer works ( ie : {{ app.config.general.xxx }}  ) , the get() method must be used.

Fix samples of config value access

---

source/extensions/essentials.md

That has confused me as I started with my first extension.

fixed config filename and add explanation where to find the real config file

---

source_docs/internals/bolt-internals.md
source_docs/storage/entities.md
source_docs/storage/entity-manager.md
source_docs/storage/entity-metadata.md
source_docs/storage/entity-transforms.md
source_docs/storage/introduction.md
source_docs/storage/repositories.md

**Note for the OCD Crew:**
Yes, I am looking at you, @CarsonF :grin: 
I have changed the storage documents to refer to Bolt v3.0 as it is not linked in the menus, and can be removed once we are ready to branch versions of this.

Remove 2.3 references

---

.gitignore
composer.json
console
index.php
src/Command/BuildDocumentation.php

Console command `./console bolt:build-docs 2.2 master` creates version folder for each of the passed in branches and outputs the version content to `version/xxx/` 
It also outputs a `versions.yml` file to git allowed version prefixes to access via request, so in the above example `docs.bolt.cm/2.2/introduction` and `docs.bolt.cm/master/introduction`
The `versions.yml` could also be used to make a dynamic list of links too, perhaps for the bottom of the sidebar.

Initial proposal for a multi version build

---

source_docs/extensions/building/widgets.md

The list above the example shows that the `footer` location is only available in the frontend and @bobdenotter said the example is wrong. So I fixed the example.

fix widget example

---

view/_master.twig

Assuming the `version` variable in twig holds `master` or `release-2-2` depending on which version you are.

enable versioned search results

---

menu_docs.yml

I can't find the markdown file for that page in the source. Am I blind or is it not there? Same for the `release-process` file (which doesn't need to be deleted but isn't there too.).

Remove duplicated page

---

docs/howto/muti-site-setup.md

Using composer « create-project » to create project instead of « git
clone » so you get the latest stable version automatically

Using composer to create project

---

docs/content/contenttypes-and-records.md

A non-existent template won't generate an error, it will just fall back to previous candidates.

Fix references to error in case of non-existent template

---

docs/getting-started/installation.md

- a lot of broken anchors
- download was for bolt-latest, which is the 3.0 branch at this time. Downloading 3.0 and trying to configure as a 2.2 is asking for trouble
- downloadlink was no https -> broken downloadlink
Idea: Also release a bolt-2-latest.zip, for easy of linking in these docs and downloading-links?

update 2.2 docs

---

docs/storage/repositories.md

The example code for findOneBy was using findBy instead of, err… findOneBy.

Fixed wrong call to findBy in findOneBy example

---

docs/getting-started/requirements.md

Fixed typo. 'mb_string' should be 'mbstring'

Fixed typo

---

docs/configuration/introduction.md

Added an explanation where Twig may need to use the `general` namespace of the config if the user added the variable directly into `config.yml`.

Added note regarding Twig and config.yml namespaces

---

docs/templates/building-templates.md

Changed 'searchresults.twig' to correct default 'search.twig'
Both 'config.yml' and the default theme's 'theme.yml' have search.twig
as default. Updated docs to reflect that.

Changed 'searchresults.twig' to correct default 'search.twig'

---

cheatsheet.yml
docs/internals/container-service-references.md

Only for 3.0 since the cheatsheet is MIA i 2.2

app['paths'] :fire:

---

docs/fields/repeater.md

Same as previous PR, just for the Repeater field which is only available in Bolt 3.0 and above.

Repeater field cleanup

---

docs/extensions/custom-bootstrapping.md

This PR is aimed at superseding #490, and also finally documents the `application` parameter that can be used in the loader configuration file (`bolt.yml` or `bolt.php`).
We are trying to also point to a more modular approach to our loading/configuration that has been worked on heavily by the team collectively, and obviously there is still work to be done in core.
Something that this effort by @CarsonF and myself is about, is trying to make some initial steps in improving the communication to all, by those actually doing the initial core work.
What I hang my head in shame about right now, is that this supersedes @rossriley's work on #490, and he's probably the best of all of the back-end team members at documenting stuff, and he's put in a fair amount of effort, but only missed because …

Update bootstrapping guide

---

view/templates/_versionselect.twig
view/templates/index.twig

Before: 
After: 
- The label makes more sense
- You can see what is the current stable release, and which is "future release"
- If the `var/versions/` folder contains non-numeric folders, list them at the bottom.

[RFC] Improving the 'version select dropdown'.

---

src/Documentation.php

Make sure we get paths in the correct order, instead of something undefined

Fixed: Path order on live site in correct order.

---

docs/content/contenttypes-and-records.md
docs/content/permissions.md
docs/extensions/essentials.md
docs/fields/common.md
docs/fields/select.md
docs/getting-started/about.md
docs/getting-started/installation.md
docs/getting-started/introduction.md
docs/howto/building-multilingual-websites.md
docs/howto/resource-contenttype.md
docs/howto/sortingorder-in-contenttypes.md
docs/internals/the-model.md
docs/manual/contenttypes.md
docs/templates/templates-routes.md

Replace "contenttype" & "Contenttype" with "ContentType"
This was orignally targetted by @SahAssar at 3.0 … but moving it backwards now for easier merges

ContentType branding

---

docs/howto/resource-contenttype.md

This added the use of the term "blocks", in line with 3.x, and hopefully makes them a bit easier to understand.
When this goes in, I will submit a second PR post branch merge that updates this for 3.x specifically, including mentioning their existance in the default contentypes.yml

Update "Making a Resource ContentType"

---

docs/contenttypes/taxonomies.md

Will need applying to `release/3.1` and `release/3.2`.

Added a line showing how to access the taxonomy slug

---

docs/templating/templatetags.md

describe when setting width OR height to zero that thumbs resizes proportionally

Add thumbnail autoscaling to documentation

---

docs/installation/install-command-line.md

To avoid any confusion, since after the installation you only have the .dist files

Set correct names for composer .dist files

---

docs/templating/templatetags.md

Only for 3.3 and up, because of the nasty `template_from_string` hack. Thanks, @carsonf 😘

Replacement for "defined for extensions", for 3.3+ only.

---

docs/fields/html.md

- Add the abbreviation for WYSIWYG.
- Apply a tip from the W3C: https://www.w3.org/QA/Tips/noClickHere.

Change to more semantic link.

---

docs/fields/geolocation.md
docs/fields/hidden.md
docs/fields/imagelist.md
docs/fields/repeater.md
docs/fields/select.md

I read [your previous comment](https://github.com/bolt/docs/pull/631#issuecomment-274316752) about versions 3.0 and 3.2, but I started some commits in 3.2 already, I don’t have much time these days, and I believe you’ll be faster to rebase properly based on your knowledge of the workflow. Sorry to add some work.
- `example below` and `following example`. This is about not assuming where some content will visually be, but where it will sit in the flow of the text: If the documentation is printed, for example, then some content at the top of next page is not below, but always following or preceding.
- I simplified a few sentences; sometimes removing text that I found redundant. I prefer simple sentences, so let me know if that was too much. :)
- Use identical naming for `drop-down list`.
- …

Some fixes and cleanup

---

docs/extensions/intermediate/customfields.md

When we set the key in the loop the we couldn't get the current saved value with context.content.get(key). Also use `|humanize` on the label instead of `|capitalize` on the saved key (wut?).

Fix key variable being overwritten in loop

---

docs/upgrading/updating.md

Related an issue I had twice after updating from 3.1 to 3.2 with /app/cache/production not having the correct permissions.
https://boltcms.slack.com/archives/general/p1486394131011459 
Not sure if this deserves a `p class="note"` - too many notes might become chaotic.

Update updating.md (add link to permissions story in update instructions)

---

docs/templating/templatetags.md

0 was taken out because `0 !== null ` a while ago.

Add null for proportional resizing

---

docs/extensions/advanced/unit-testing.md

The init.php file is removed from 3.x. To avoid confusion the step about this was removed.

Remove deprecated step about obsolete init.php

---

docs/extensions/basics/web-assets.md

Just reading some docs I saw this. Maybe a typo? 
Opening PR so it can be changed for the better.

Typo fix in `docs/extensions/basics/web-assets.md`

---

docs/configuration/menus.md

In the submenu, one of the items had no path or link. This results in an error in the default (base 2016) bolt menu twig.

Example code gave error in strict variables mode

---

docs/getting-started/requirements.md

It is (optionally) used by `ircmaxell/security-lib` and `PasswordLib/PasswordLib`, but neither package require it
Related: https://github.com/bolt/bolt/pull/6553

Remove requirement on (optional) gmp PHP extension

---

cheatsheet.yml

Prevents docs from breaking under the latest symfony/yaml v3.2.7.
Before:

Remove trailing whitespace from cheatsheet.

---

docs/extensions/bundled/activation.md
docs/extensions/bundled/autoloading.md
docs/extensions/bundled/file-location.md
docs/extensions/bundled/index.md
docs/extensions/bundled/introduction.md
docs/extensions/index.md
docs/upgrading/index.md
docs/upgrading/migrating-local-extensions-33.md

This upgrade guide should cover the move of local extensions during the upgrade to 3.3.
There's one bit still to cover which is the asset sync, but we need to have a further discussion on what strategy we are going to recommend for this.

Local extension migration guide

---

docs/performance/index.md
docs/performance/request-cache/index.md
docs/performance/request-cache/introduction.md
docs/performance/request-cache/symfony-proxy.md

This is a re-visiting of #573 now that we have a section to put it in :smile: 
For historical reference, I still agree that config-specific parts should be centralised at some point, but that is out of scope for this addition, and can be done as a doc-wide change in a later … volunteers welcome :wink:

Symfony Reverse Proxy docs

---

docs/extensions/bundled/introduction.md

Prevents the double `/bundled/bundled/` in the docs.

Fix duplicate slugs

---

docs/upgrading/migrating-local-extensions-33.md

Just sayin':
```
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "dump-autoloader" is not defined.
Did you mean one of these?
dumpautoload
dump-autoload
```

Command "dump-autoloader" is not defined.

---

docs/getting-started/requirements.md

Goes with https://github.com/bolt/bolt/pull/6748

Remove ext-mbstring as a requirement.

---

docs/extensions/basics/web-assets.md

* setPriority for widgets is already implemented here, this just adds docs: https://github.com/bolt/bolt/blob/master/src/Asset/Widget/Widget.php#L270-L275
* Making the examples for priority 99 seems pretty odd, this changes them to 5 and changes the text to make it more clear that it sets the order, not just pushing a single asset/widget to the bottom.
* Also fixes some long lines in the widget section.

Add setPriority for widgets and more sensible defaults for priority

---

docs/extensions/bundled/activation.md

Current 3.3 documentation shows that .bolt.php should return an array of new instances of bundled extensions to load. In reality this should actually be an array of fully-qualified class names.

Update Bundled Extension Activation

---

docs/extensions/intermediate/controllers-routes.md

This changes the docs to extend the base controller — as intended by design — giving extension developers access to the built in helpers and making like generally easier for them.
:koala: !

[3.0] Simplify controller example

---

docs/performance/index.md
docs/performance/remote-filesystem/amazon-s3.md
docs/performance/remote-filesystem/index.md
docs/performance/remote-filesystem/introduction.md

These are the starter docs for using Amazon S3 as a remote filesystem in Bolt :tada: 
I would like to point out that a huge amount of work on the Bolt & Filesystem repositories, and most of the example code here is thanks to @CarsonF … seriously, if you knew the hours that have gone into making this happen! :smile: :+1:

Bolt 3.3+ Amazon S3 Remote Filesystem

---

docs/extensions/basics/web-assets.md

Promised follow-up to https://github.com/bolt/bolt/pull/6825

[3.3] Add web asset factory methods to fluent examples

---

view/templates/_versionselect.twig
view/templates/index.twig

Updating links to github, without the `release/`.

---

docs/internals/javascript-css-build.md

Update to document Yarn use, and this also includes the rename in #817 which will just do its thing on cascade.
For fun I tested this on a fresh minimal CentOS 7 install just adding the package repositories linked in the upstream documentation, and everything built perfectly.

[3.2] Update asset build

---

docs/contenttypes/taxonomies.md

Easier to review this one by commit. I'll send the first one down to 3.0 too so we don't end up with merge cascade "fun" later on :wink: 
A note on approach with this one:
```twig
{% for tag in record|taxonomy.tags|default %}
{{ tag }}{% if not loop.last %}, {% endif %}
{% endfor %}
```
I initially went with the discussion from Slack last night and had a conditional instead of the `|default` filter, but you can't use `loop.last` when the iterator is built with a conditional. The taxonomy filter will always return an iterable, so I thought less visual noise would be easier for the frontend crew. :woman_shrugging:

[3.4] Taxonomy filter

---

docs/fields/index.md

I know this page exist under the template section. But it is not obvious.
Thinking contextually If I am looking for documentation on templateselect field type. I would go to the field types page and not the templateing section.

add template select to list of fields

---

docs/howto/troubleshooting-outside-webroot.md
docs/installation/manual-download-and-extraction.md

For the "flat" distro, the `.bolt.yml` is required. However, if you manually extract it, `nut init` is not run, leaving you with `.bolt.yml.dist`. For those users who _both_ extract manually _and_ use the flat distro, i've expanded a bit on this in the docs.

Updating 'flat files' and 'manual extraction' sections.

---

docs/extensions/intermediate/web-assets.md

Using setType() function is not possible. That function does not exist in [Widget.php](https://github.com/bolt/bolt/blob/3.4/src/Asset/Widget/Widget.php) but correct me if I'm wrong. 
I think this changes can be merged into 3.0 and up.

Use setZone() function to define the Widget Zone

---

assets/scss/modules/_search.scss

This is pretty untested, I don't have access to a proper system ATM, but the contrast levels between the label and the background were really annoying me :)

Fix the color of "Search the documentation"

---

docs/configuration/advanced/sessions.md

Fix incorrect keys for the session configuration in `config.yml/config_local.yml`. Also provides a working example.
Bashed my head on this for a while before looking at the source code.

Fix config keys, add an example

---

docs/performance/remote-filesystem/amazon-s3.md

$name & $expire params are part of DoctrineCache rather than the Cached adapter.

Move $name & $expire variables to correct constructor for filesystem.cache_factory

---

docs/templating/record-and-records.md

The example in the docs will result in an error if you have a `templatefields` column in your content - because the value of the `templatefields` is not a string and cannot be displayed.

Add extra check in example code to prevent errors
