bolt/docs

source/installation.md
Related to https://github.com/bolt/bolt/issues/2451
=> Remove timthumb rewrite rule from htaccess

source/howto/building-multilingual-websites.md
Add link to Labels extension before I forget.
=> Add correct reference for Labels extension.

source/installation.md
=> Update git install instructions to detail choosing master and stable branches

source/extensions/essentials.md
=> Document using Twig functions in content records

source/requirements.md
.. also removed the ‘lighttpd’ comment, because no-one ever adduced for
that.
=> Added a recommendation for PHP version..

source/updating.md
I am not sure if Git installation also gives these notifications, since I've never tried that. And the text could be a little more humouristic because it's not an actual problem, but I didn't have any inspiration.
=> Chmod cache notification

source/internals/contributing.md, source/internals/release-process.md
As per https://github.com/bolt/bolt/issues/2985
=> Release process

source/requirements.md
I made this edit to make it clear that Mod_rewrite needs to be enabled. Else some things won't work.
=> Made it more clearer that Mod_rewrite MUST be enabled.

source/installation.md
* Simplify the YAML/Twig block
* Add some comments
* Don't allow PHP files to be called from upload, app, theme and extensions directories (fixes #170)
=> Update install config for Nginx

source/requirements.md
=> Note about conflicting PHP modules

source/extensions/config.md
i totally missed the testing page, so this might help other people too
=> link to testing and debugging from basic instructions

source/extensions/essentials.md
as promised in https://github.com/bolt/bolt/pull/2811
closes https://github.com/bolt/bolt/issues/1129
=> explanation of extra snippet locations

source/installation-advanced.md
=> Cosmetic on advanced installation

source/templatetags.md
=> Adding doc for "safestring" filter.

source/building-templates.md
The CSS from #190 has been cherry-picked into master to make this go "ping".
Fixes https://github.com/bolt/bolt/issues/3506
=> Add 2.2+ meta warning for Template Specific Fields

source/maintenance-mode.md
I had to look this up / was missing this information in the docs. It's might be a bit too technical for the docs, but the fact that I checked the docs before trying the feature could mean that other people are also missing this information.
=> Document 503 status code

README.md
Some people might not know markdown, some people might think they need to built the documentation or think it's not possible to just serve it.
I had to figure this out, so I think this information belongs in the docs.
=> Explain markdown and how to serve the docs

menu.yml, source/howto/resetting-a-password.md
Not sure if this (howto) is the right place to put this docs.
The user:reset-password command is an open PR bolt/bolt#3560, this PR should not be merged until the code is merged.
=> Reset password options

source/contenttypes-and-records.md
... maybe forgotten, maybe that type is a black sheep.
=> Missing markup field type

source/internals/contributing.md
=> Fix link to extensions

source/extensions/essentials.md
Classes changed, so we need to update them in docs too.
=> Updated StorageEvent(s) classes and constants

source/howto/installing-local-extensions.md
Give the info how to import/update a local extension.
Add the info that you need to run composer update to create new autoloader file.
=> Added update information for local extensions

source/extensions/essentials.md, source/internals/bolt-internals.md
=> Update 2.2 internals & extension essentials

source/contenttypes-and-records.md
Fixes #219
Obvious credit to @bobdenotter
=> Added 'listing_sort'. 

source/howto/select-field-type.md
@bobdenotter,
I added this example to the documentation!
=> Add a practical example of an hourly drop down using the select field

source/installation.md
Fixes https://github.com/bolt/bolt/issues/4171
=> Update Nginx config

menu.yml, source/howto/curl-ca-certificates.md
This is based on this [comment](https://github.com/bolt/bolt/issues/3575#issuecomment-146018366) by @dadaxr
=> Setting Up cURL SSL/TLS Certificate Authority Certificates

source/extensions/config.md
Your decision if you want to merge now or in a few days when there is real content in the extended extension starter repo.
=> add note for the extended extension starter repo

source/installation-composer.md
=> Composer Installation: Added composer requirement

source_docs/updating.md
Inspred by https://discuss.bolt.cm/d/123-updating-using-ssh-overwriting-custom-htaccess
=> Prevent overwriting .htaccess file

source_docs/templatetags.md
=> Add docs/example of multi parameter order

source_docs/building-templates.md, source_docs/contenttypes-and-records.md, source_docs/storage/entities.md, source_docs/storage/entity-manager.md, source_docs/storage/entity-metadata.md, source_docs/storage/entity-transforms.md, source_docs/storage/introduction.md, source_docs/storage/repositories.md
Because master is 3.* only. I hope I found all. Otherwise blame the one who changed the wording :P
=> Remove bolt 2.2 and 3.0 notices

index.php, src/Command/BuildDocumentation.php, view/_sub_contents.twig, view/_sub_submenu.twig, view/index.twig
Some minor fixes to enable the multiple versions to work correctly
=> Fix links for versioned docs

source_docs/contenttypes-and-records.md
Documentation for the allow_numeric_slugs option, see PR https://github.com/bolt/bolt/pull/4784
=> docs for allow_numeric_slugs option

source_docs/upgrading/moving-22-30.md
First version of a migration page
=> Bolt 3 migration guide

source_docs/installation.md
=> add docs for dynamic replacement feature

view/_master.twig, view/index.twig, view/source/scss/_algolia.scss, view/source/scss/docs.scss, view/styles/docs.css
Styles should work for now, otherwise :hamster: can change them like he wants :)
=> Algolia search

menu_docs.yml
Note: Don't deploy this! It will break, but the v3 version needs the menu in this format to "snapshot" it.
=> Updating menu in preparation for New Bolt 3 docs.. 

menu_docs.yml, source_docs/fields-tag.md, source_docs/record-and-records.md
Adding docs for `fields()`-tag.
=> Adding docs for fields

source_docs/extensions/testing.md, source_docs/howto/making-sure-htaccess-works.md, source_docs/screenshots.md
=> Fixing paths to images.

source_docs/installation/composer/creating-a-new-project.md
Fixes https://github.com/bolt/bolt/issues/5101
=> Tweak Composer installation

source_docs/relationships.md
As implemented here:
https://github.com/bolt/bolt/blob/release/2.2/app/view/twig/editcontent/_relationships.twig#L17
=> [2.2] Document relationship title format

source_docs/relationships.md
As implemented here:
https://github.com/bolt/bolt/blob/release/3.0/app/view/twig/editcontent/fields/_relationship.twig#L4
=> Document relationship title format

source_docs/extensions/building/controllers-routes.md
=> Fix controller class name

view/source/package.json, view/source/scss/_settings.scss, view/source/scss/_variables.scss, view/source/scss/docs.scss, view/templates/_master.twig, view/templates/index.twig, web/.htaccess, web/js/docs.js, web/styles/docs.css
Cleaned up a lot and refactored issues from the new foundation. Put in moar prettiness!
=> Restyling of docs site - more like Bolt mainsite

cheatsheet.yml
Fixes one part of bolt/site-v20/issues/19
=> Add fields to functions section in cheatsheet

docs/content/contenttypes-and-records.md
=> Clarify slug generation for #362

docs/extensions/basics/creating.md
=> Update creating.md. Letter missing.

docs/extensions/advanced/customfields.md
Maybe a typo. "of" instead of "or"?
=> Update customfields.md Possible typo.

docs/howto/troubleshooting-outside-webroot.md
Fixes https://github.com/bolt/bolt/issues/5396.
=> Provide an extra option

docs/extensions/building/web-assets.md
=> Add note about local assets to fix #4047

docs/configuration/introduction.md, docs/manual/fieldtypes.md
=> Add google api key to docs

docs/getting-started/requirements.md
Added missing required extensions, needed for file management / thumbnails.
=> Added missing required extensions

docs/templates/fields-tag.md
Related commit:
https://github.com/bolt/bolt/pull/5310/commits/69e698837ef889c3081182a795ea7734655ff8dc
=> Updated docs after imagelist was made an "extended" field

docs/extensions/building/web-assets.md
Better to link to one place that explains it than having multiple places to update.
See #423 vs. #429
=> Smaller *is* better, see #423 vs. #429

docs/other/nut.md
Related https://github.com/bolt/bolt/pull/5483
=> Update nut to include user:manage

docs/templates/content-fetching.md
=> Created a reference to the setcontent documentation for randomising content fetches

docs/storage/directives.md, docs/storage/handlers.md, docs/storage/index.md, docs/storage/queries.md
Here is some documentation about the Bolt V3 layer. This might be something that @rossriley may want to go over. This is also in reference to https://github.com/bolt/docs/issues/452
=> Storage Additions

docs/extensions/basics/creating.md, docs/extensions/basics/store-visual-assets.md
this is for #456 .  
under basics -> creating -> publishing the copy could use some work IMO. 
Have a look at this gang.. lemme know what you all would like changed if it needs anything!
=> Adds Marketplace Visual Assets page

cheatsheet.yml, docs/howto/boilerplate-for-multilingual-websites.md, docs/howto/building-multilingual-websites.md, docs/other/locales.md, docs/templates/templatetags.md
=> localdate -> localedatetime

docs/extensions/advanced/storage-tables.md
=> Fix namespace

docs/fields/geolocation.md, docs/fields/imagelist.md, docs/fields/intro.md, docs/fields/video.md, docs/templates/record-and-records.md
They belong under their respective field.
Also titlecase the page title.
=> Move field specific templating instructions

src/Controllers.php
please merge this **after** we deployed the first bit of the new structure.
=> 404 page: link notice for restructured documentation

docs/installation/composer/creating-a-new-project.md
This makes much more sense than before.
=> change composer create-project to composer install command

docs/extensions/basics/index.md, docs/extensions/basics/translations.md
This is a real basic overview of how to use Translations with Extensions. Simple but sweet... 
Closes https://github.com/bolt/docs/issues/493
=> Added Translations documentation.

README.md
=> Updating README for `release/2.2`, to keep them in sync.

cheatsheet.yml
=> Better explanation of 'show in menu' option

view/templates/index.twig
=> Add autofocus on algolia search input

docs/fields/file.md, docs/fields/filelist.md, docs/fields/image.md, docs/fields/imagelist.md
=> Fix options in file, filelist, image and imagelist field types

docs/fields/checkbox.md, docs/fields/common.md, docs/fields/date.md, docs/fields/datetime.md, docs/fields/file.md, docs/fields/filelist.md, docs/fields/float.md, docs/fields/geolocation.md, docs/fields/hidden.md, docs/fields/html.md, docs/fields/image.md, docs/fields/imagelist.md, docs/fields/integer.md, docs/fields/intro.md, docs/fields/markdown.md, docs/fields/select.md, docs/fields/slug.md, docs/fields/templateselect.md, docs/fields/text.md, docs/fields/textarea.md, docs/fields/video.md
Fixed some stuff that triggered my OCD and added code block language definitions.
=> Fields Cleanup

README.md
@PhillippOhlandt This should fix the problems you were seeing on a **fresh clone**
=> Update git worktree examples

src/Controllers.php, view/templates/_macros.twig, view/templates/_master.twig, view/templates/sitemap.twig, view/templates/sitemap_list.twig
=> Add Sitemap.xml functionality.

docs/other/index.md
=> On second thought , let’s not go to Stack Overflow.

docs/templates/building-templates.md
record is, so let's use it in the examples.
=> content is not a preset twig variable,

docs/configuration/index.md, docs/configuration/thumbnails.md
Preparation for adding documentation about thumbnail aliases in 3.2.
Feel free to suggest text changes :)
=> Add thumbnails configuration page

docs/content/contenttypes-and-records.md, docs/content/menus.md, docs/content/permissions.md, docs/content/relationships.md, docs/fields/textarea.md, docs/getting-started/installation.md, docs/templates/building-templates.md, docs/templates/templates-routes.md
Converting some more lists with stuff to tables.
Next up: PR for `site` that slightly tweaks the layout of these tables.
=> Converting some lists to tables, where appropriate.

docs/content/content-in-templates.md, docs/content/menus.md, docs/content/permissions.md, docs/content/relationships.md, docs/content/taxonomies.md, docs/extensions/essentials.md, docs/fields/select.md, docs/howto/boilerplate-for-multilingual-websites.md, docs/howto/building-multilingual-websites.md, docs/howto/sortingorder-in-contenttypes.md, docs/internals/the-model.md, docs/manual/content-overview.md, docs/manual/contenttypes.md, docs/manual/dashboard.md, docs/manual/edit-content.md, docs/manual/fieldtypes.md, docs/templates/building-templates.md, docs/templates/content-fetching.md, docs/templates/content-paging.md, docs/templates/content-search.md, docs/templates/record-and-records.md, docs/templates/templates-routes.md
Part 2 of #554
Lesson learned, `ack` & `perl` beat PhpStorm for text processing *hands down* :wink:
=> More replacements of contenttype with ContentType

docs/content/contenttypes-and-records.md, docs/content/taxonomies.md
=> I did some light editing on the Taxonomies documentation

docs/configuration/thumbnails.md, docs/templating/templatetags.md
A bit light on the twig part, because there is still a big refactor on my list which will clean all the mess up.
=> Add documentation for thumbnail aliases

docs/howto/resource-contenttype.md
Follow up from #565 for 3.x specific changes
=> Update "Making a Resource ContentType" for 3.x

docs/howto/performance-tips.md
=> Adding analyze;

src/Application.php
=> Setting the default to correct version 3.2.

docs/getting-started/introduction.md
It's not coming soon. Let's stop kidding ourselves.
=> Let's stop pretending and being optimistic.

class_reference.yml
=> Updating class_reference for 3.3

docs/extensions/intermediate/service-providers.md
Adds the "proper" way to register a service provider for #613
=> Fix for #613

class_reference.yml
As previously discussed: The delta in this one is large, because i've alphabetized the output.. Going foward this should give more consistent results. 
PR's for other versions follow shortly.
=> Updating class reference for Bolt 3.2.x

src/PageBuilder.php
=> Strip tags in generated anchors.

docs/extensions/config.md, docs/extensions/dev.md, docs/extensions/introduction.md, docs/extensions/testing.md, docs/howto/building-multilingual-websites.md, docs/howto/performance-tips.md
Follow-up for bolt/bolt#6234 for 2.2+
=> Switch extensions.bolt.cm to market.bolt.cm

docs/howto/installing-local-extensions.md
This is the updated local extension documentation to walk-through how-to get them setup and loaded as per the new local extension PR bolt/bolt#6170
=> [WIP] First version of new local extension docs

docs/installation/install-command-line.md, docs/installation/install-git-clone.md, docs/installation/install-sftp.md
The changes are straightforward. Let me know if I should make these changes from a different branch instead.
=> Fix awkward sentence describing server config

docs/fields/select.md
Added multiple contenttypes documentation to the selectfield docs.
=> Select field docs update 

docs/extensions/custom-bootstrapping.md, docs/howto/installing-local-extensions.md, docs/installation/composer/creating-a-new-project.md, docs/upgrading/moving-22-30-advanced.md
This should update (all?) the path docs relevant to https://github.com/bolt/bolt/pull/6166
=> Update paths use

docs/howto/building-multilingual-websites.md
Change hypen to underscore because hypen is not allowed in contenttypes.yml
=> hypen cannot be used in contentypes.yml file

docs/getting-started/requirements.md
See why: https://github.com/bolt/bolt/issues/5014 and https://github.com/bolt/bolt/issues/5746#issuecomment-250705296
=> add a note about a needed hostname or fqdn

docs/contenttypes/intro.md
Credit to @marcingajda for pointing this out :+1:
=> Update links in ContentTypes intro

docs/core-development/ide-tools.md
If someone could be so kinda as to quickly check and merge this, I'll update the v3 one with a new PR post-cascade.
=> Core development page "IDE Tools for developing Bolt"

docs/internals/bolt-storage-internals.md
Work in progress, no need to merge yet.
=> Storage Internals Documentation

docs/howto/using-php-built-in-web-server.md
=> Update "Running Bolt using PHP's built-in web server" for Bolt v3

cheatsheet.yml
only works on certain fields, as said in docs.
=> clarification on 'required' option

docs/getting-started/requirements.md
Supporting PR for https://github.com/bolt/bolt/pull/6485
=> [4.0] Raise minimum requirement to PHP 7.0

docs/internals/filesystem.md, docs/internals/index.md
Probably needs breaking up down the track, definitely needs more love … but it is a start.
=> Base documentation on using the file system layer

docs/configuration/thumbnails.md, docs/extensions/basics/testing.md, docs/howto/multi-site-setup.md, docs/installation/composer/adding-to-an-existing-project.md, docs/installation/composer/creating-a-new-project.md, docs/upgrading/moving-22-30-basic.md, docs/upgrading/moving-22-30.md
Will be followed up by a small PR for `site`.
=> Replacing hardcoded version numbers with '%%VERSION%%'.

docs/upgrading/moving-22-30.md
=> Update link to market place, as old link is a 404

docs/extensions/filesystem/working-with-files.md
You know you're having/had one of those days when …
=> Correct method used to delete files, and added exception hint

view/templates/classreference.twig
- make table fit on screens less than 1920 pixels wide. 
- Add links to Symfony and Silex API docs.
=> Update "Class reference" page

docs/extensions/basics/twig.md, docs/extensions/intermediate/index.md, docs/extensions/intermediate/twig.md
Add a dedicated part to create his own Twig extension in a separate file.
=> Add a dedicated part to create his own Twig extension in a separate file.

docs/debugging/index.md
After this is merged and cascade, I'll PR 3.3 with the recent changes to core by @CarsonF
=> Add introductory information to debugging index

docs/getting-started/introduction.md, docs/howto/troubleshooting-outside-webroot.md, docs/installation/install-command-line.md, docs/installation/install-sftp.md, docs/installation/installation.md
- Adding more links to "flat distro" 
- Pointing out that "easy and recommended" is in fact easy, as well as recommended.
- Fixing broken links on opening page.
=> Making some smaller changes.

view/templates/_master.twig
As reported by @harikt on twitter. Thanks! 👍 
https://twitter.com/harikt/status/855477515426705411
=> Add clearfix div, to prevent flow issues.

docs/nut-command/introduction.md
=> Rewrite the introduction for Nut

docs/howto/index.md, docs/index.md, docs/performance/index.md, docs/performance/introduction.md
This starts the breakout of the HOWTO into a performance section, most notably to include the HTTP Cache reverse proxy section that I'll PR when this cascades to `release/3.2`
=> Performance section

docs/howto/resource-contenttype.md
Goes with https://github.com/bolt/bolt/pull/6614
=> Replace use of {{ link() }}

docs/templating/linking-in-templates.md
Also goes with bolt/bolt#6614.
=> Add small 'working with editor-provided' links section

composer.json, composer.lock
=> Update site to Twig 2

docs/templating/linking-in-templates.md, docs/templating/templatetags.md
- combining `url` and `path`
- adding `canonical`
- update incoming links.
Feel free to squash when merging in :-)
=> Updating links page

docs/fields/html.md
Example now includes entities and entities_latin with explanation of what they store
=> Added a new working example to the HTML editor field type

docs/fields/file.md, docs/fields/filelist.md, docs/fields/imagelist.md
Not entirely sure that you have to create the directory manually, so please doublecheck this.
=> Mention 'upload' option (1)

docs/internals/container-service-references.md
This isn't everything, and will need updates/additions at various minor branch points … 
It cleans out the old cruft, and if I haven't made mistakes with the current content please feel free to PR your own additions in later PRs. 
This PR's scope is limited to getting rid of what we don't want publicly advertised deprecated approaches/services.
=> Initial rework of the internals "Container Service References"

docs/configuration/advanced/index.md, docs/configuration/advanced/sessions.md, docs/configuration/index.md
This is option B) for https://github.com/bolt/bolt/pull/6771 and heavily documents available storage configuration, give examples, links to upstream as appropriate, and warnings & advice notes where appropriate/important.
I've initially aimed this at 3.2 as I seem to remember there being problems earlier, if I am wrong, let me know and I will target either 3.0 or 3.3.
Also this is basically written from the top of my head, with looks at 3.2 & 3.3 SPs, but not tested … so :koala:
=> Initial documentation on session configuration

docs/fields/file.md
=> Fix indentation

docs/fields/image.md
This seems to have gotten lost from #754
=> Mention 'upload' option in image too

docs/installation/install-git-clone.md, docs/nut-command/setup/setup-sync.md
Includes #767 
Relative to https://github.com/bolt/bolt/pull/6816
=> [3.3] Updates for bolt/themes

docs/extensions/basics/web-assets.md
Goes along with https://github.com/bolt/bolt/pull/6826
=> [4.0] Asset priorities

docs/fields/geolocation.md
Changed http to https in embed example. (http requests are not allowed)
=> Update geolocation page

docs/fields/slug.md
Closes https://github.com/bolt/bolt/issues/6847
=> Add a note about `Permalink` vs. `Unique Alias`.

view/templates/classreference.twig
=> Drop `release/` branch prefix

docs/manual/contenttypes.md
line 25 as per the github editor
=> 'thouch on' typo changed to 'touch on'

docs/internals/task-scheduler.md
… about 15 months later :disappointed:
=> Update extending cron for v3

docs/extensions/basics/creating.md
This was "smashed out" on my keyboard, and with wilting amount of brain power and energy. If anyone wants to be super-fussy can they just merge and PR some fixes. Kinda getting exhausted :rofl:
=> Rewrite "Creating a New Extension" for Bolt 3.3

docs/configuration/routing.md, docs/internals/routing.md
May 10 … **2016**
Lets not repeat that shortcut again, hey. :angry:
=> More v2 clean up … 15 months later

docs/configuration/database.md
This is sort of an important thing.
=> Document the prefix option

docs/configuration/database.md
=> Remove sqlite FUD

docs/extensions/basics/twig.md
Please double check the accuracy of the information provided.
=> Add some info on twig namespacing

docs/extensions/storage/directives.md
Fixes https://github.com/bolt/bolt/issues/6894
Update the docs to use the extend syntax when adding directives.
=> Extend the parser to add directives

docs/extensions/basics/creating.md
Relative to https://github.com/bolt/bolt/pull/6934
=> [3.3] Add detail on option to prevent Composer symlinking path repos

docs/upgrading/moving-22-30-basic.md
Is there any good way to test this before merging?
Fixes #810
=> Correct broken 'Routing' link.

docs/extensions/basics/creating.md
- Ensure the path repo has priority in case the extension also exists on the Marketplace
Massive amounts of thanks to @cdowdy for working with me to figure out what was going wrong here :+1:
=> Extension local repo clarification

docs/nut-command/config/config-set.md
=> Corrected misspelling of "field"

docs/contenttypes/intro.md
See discussion in bolt/bolt#7012
=> Add note about internal use of double underscore prefix

docs/templating/twig-functionality.md
Added example to get imageinfo from images in imagelists
=> Example to get imageinfo from images in imagelists

docs/fields/common.md
!- I have used this in 2.2.X, not sure if it still works in Bolt 3
=> Add link remark in Prefix/Postfix

docs/howto/using-php-built-in-web-server.md, docs/nut-command/setup/setup-deploy.md
=>  Additional notes on leveraging setup:deploy functionality

docs/howto/resource-contenttype.md
Close tag and use relative_path function
=> Update resource-contenttype doc

docs/content/taxonomies.md
=> spotted typo

docs/extensions/filesystem/working-with-directories.md, docs/extensions/filesystem/working-with-files.md
=> Correct variable name, and make ordering clearer

docs/extensions/intermediate/customfields.md
=> fixed wrong class signature

docs/extensions/storage/repositories.md
Added methods findWith and findOneWith
=> Repositories docs update

docs/fields/html.md, docs/fields/markdown.md, docs/fields/text.md, docs/fields/textarea.md
See also: https://github.com/bolt/bolt/pull/7169
=> Add small description of sanitisation.

docs/configuration/index.md, docs/configuration/reading.md
Covers php, twig and the new environment and service lookup syntax.
=> Add new page about reading and accessing configuration values

docs/templating/twig-functionality.md
Maybe there's other places in the docs that link to this?
=> Fix internal link to thumbnail

docs/templating/linking-in-templates.md
A section on using this method is probably also needed.
=> absolute_url info added

docs/templating/linking-in-templates.md
=> Added section about `absolute_url`

docs/extensions/intermediate/admin-menus.md
Goes with https://github.com/bolt/bolt/pull/7252
=> Adding a section about adding submenus in extensions

docs/howto/troubleshooting-outside-webroot.md, docs/installation/manual-download-and-extraction.md, docs/installation/quick-install.md
Closes https://github.com/bolt/bolt/issues/7289
=> Making it clearer that one really must rename all four files for 'Flat distribution'.

docs/contenttypes/taxonomies.md
I think this is enough to make people realise that these options exist.
=> Add prefix/postfix examples

docs/configuration/menus.md
Added missing documentation for dynamic menu functionality
=> Add 'limit' to Dynamic Menu example

docs/templating/template-selection.md
Fixed some text where "overview" was used instead of "single" record/page.
=> Fixed some text where "overview" was used instead of "single" record/page

docs/fields/float.md, docs/fields/integer.md, docs/fields/text.md, docs/fields/textarea.md
Just mentioning that this is possible currently.
=> Placeholder option

README.md, composer.lock
Some minor updates to the docs website.
=> Updating Docs site (and README)

docs/fields/block.md, docs/fields/repeater.md
See https://github.com/bolt/bolt/pull/7443
=> Add description for collapsible for Block and Repeater fields

docs/fields/embed.md
Took info from 3.5 release notes and also from the video field since it's a bit similar.
=> New embed field type in 3.5

docs/howto/making-sure-htaccess-works.md
Added some pointers to solving Apache not reading the .htaccess file.
=> Solving: Apache not reading .htaccess

docs/howto/index.md, docs/howto/setting-up-sites-to-be-extendable.md
This one is aimed at trying to give end users a little more direction about how to setup their projects
to be more easily extendable.
Includes sections on adding your own controller route/action and how to use the new built in bundle to add your own custom twig features.
=> New how-to making Bolt Projects Extendable

docs/manual/fieldtypes.md
Just a quick add of the date and datetime to the manual. I wasn't sure where to add the images at, so i have included them to this PR as well.
=> Added to the manual date and datetime as field types.

docs/fields/common.md
Select fields that have their own set of values or fields that load a list of records from another ContentType
=> Add info on default values for select fields

docs/performance/introduction.md
I've seen production websites more than halve their response time
by optimizing the autoloader, and the base install of bolt 3.5
gives a 20% speed boost after optimizing on my development machine.
=> Performance: Mention autoloader optimization

docs/configuration/permissions.md
Describe what can cause of lot of inserts into database.
=> Mention debug_permission_audit_mode

docs/configuration/thumbnails.md
because broken links are evil. very bad link.. baaaad link.
=> Fix broken link

docs/installation/webserver/nginx.md
Added documentation for installing bolt in a subfolder.
=> Added documentation for installing Bolt in a subfolder on NGINX

docs/extensions/intermediate/customfields.md
In my environment the injector won't work without this
=> setZone controller
